"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](fg:#adc6ff)\
$os\
$username\
[ ](bg:#bfc6dc fg:#adc6ff)\
$directory\
[ ](bg:#debcdf fg:#bfc6dc)\
$git_branch\
$git_status\
[ ](bg:#2b4678 fg:#debcdf)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[ ](bg:#3f4759 fg:#2b4678)\
$conda\
$docker_context\
[ ](bg:#583e5b fg:#3f4759)\
$time\
[ ](fg:#583e5b)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#adc6ff fg:#102f60"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#adc6ff fg:#102f60"
style_root = "bg:#ffb4ab fg:#690005"
format = '[ $user ]($style)'

[directory]
style = "bg:#bfc6dc fg:#293041"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#debcdf fg:#402843"
format = '[ $symbol $branch ]($style)'

[git_status]
disabled = true

[nodejs]
symbol = ""
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = " "
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "bg:#2b4678 fg:#d8e2ff"
format = '[ $symbol( $version)(\($virtualenv\)) ]($style)'

[docker_context]
symbol = ""
style = "bg:#3f4759 fg:#dbe2f9"
format = '[ $symbol( $context) ]($style)'

[conda]
symbol = "  "
style = "bg:#3f4759 fg:#dbe2f9"
format = '[ $symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:#583e5b fg:#fbd7fc"
format = '[   $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ❯](bold fg:#adc6ff)'
error_symbol = '[ ❯](bold fg:#ffb4ab)'
vimcmd_symbol = '[ ❮](bold fg:#adc6ff)'
vimcmd_replace_one_symbol = '[ ❮](bold fg:#debcdf)'
vimcmd_replace_symbol = '[ ❮](bold fg:#debcdf)'
vimcmd_visual_symbol = '[ ❮](bold fg:#bfc6dc)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:#e2e2e9"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[package]
disabled = true
